layout_spectrum: 1
typography_spectrum: 0.4972015
color:
  saturation: 0.6245336
  lightness: 0.7896455
  brandStrength: 0.8222118
  brandColors:
    - '#CF0114'
    - '#004040'
    - '#449EA7'
    - '#B8C7D2'
    - '#E1858D'
  rhythmicContrast: 0.8418843
name: 'Alicia Leal - SYMBOLE, MYSTERIEN UND LEBEN'
