name: Alicia Leal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4972015
title: 'SYMBOLE, MYSTERIEN UND LEBEN'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#CF0114'
    - '#004040'
    - '#449EA7'
    - '#B8C7D2'
    - '#E1858D'
  brandStrength: 0.1875
  lightness: 0.7896455
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
